apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: finance
  annotations:
    desc: Ini adalah Aplikasi NGINX
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80