version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: max
      # MONGO_INITDB_ROOT_PASSWORD: secret
      # - MONGO_INITDB_ROOT_USERNAME=max
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net
  backend:
    build: ./backend
    container_name: goals-backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '80:80'
    volumes:
      - logs:/home/app/logs
      - ./backend:/home/app
      - /home/app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: goals-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/home/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  # Names Volume
  data:
  logs: