@startuml LoadBalancer
node "Kubernetes Cluster" {
  node "Node 1" as N1 {
    node "Pod Service A" as N1P1
    node "Pod Client" as N1P2
  }
  node "Node 2" as N2 {
    node "Pod Service A" as N2P1
    node "Pod Service A" as N2P2
  }

  [Service Load Balancer] as S
  S --> N1P1
  S --> N2P1
  S --> N2P2
}

node Client as C
node LoadBalancer as LB

C --> LB
LB --> N1
LB --> N2
N1 --> S
N2 --> S
@enduml