apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: env
        operator: In
        values:
          - staging
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: staging
    spec:
      containers:
      - name: nginx
        image: nginx 
        ports:
        - containerPort: 80