@startuml DirectAccessPod
node "Kubernetes Cluster" {
  node "Node 1" as N1 {
    node "Pod Service A" as N1P1
    node "Pod Client" as N1P2
    node "Pod Service B" as N1P3
  }
  node "Node 2" as N2 {
    node "Pod Service B" as N2P3
    node "Pod Service A" as N2P1
    node "Pod Service A" as N2P2
  }

  N1P2 --> N1P1
  N1P2 --> N2P1
  N1P2 --> N2P2
}
@enduml